plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':module-common')
    implementation project(':module-domain')
    implementation project(':module-ai')
    implementation project(':module-chat')

    testImplementation project(':module-common')
    testImplementation project(':module-domain')
    testImplementation project(':module-ai')
    testImplementation project(':module-chat')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.modulith:spring-modulith-starter-core'
    implementation 'org.springframework.modulith:spring-modulith-starter-jpa'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    runtimeOnly 'com.h2database:h2'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // spring modulith docs
    testImplementation "org.springframework.modulith:spring-modulith-docs:1.4.0-SNAPSHOT"
}

repositories {
    mavenCentral()
    maven { url "https://repo.spring.io/snapshot" }
}

test {
    doFirst {
        println "Test Classpath: " + classpath.asPath
    }
}