global:
  scrape_interval: 15s #메트릭 수집 주기 15초
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'backend-blue'
    metrics_path: /api/actuator/prometheus
    static_configs:
      - targets: ['backend-blue:8080']

  - job_name: 'backend-green'
    metrics_path: /api/actuator/prometheus
    static_configs:
      - targets: ['backend-green:8080']