spring:
  profiles:
    active: local
    include: secret

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}        # 환경변수로 관리
            client-secret: ${GOOGLE_CLIENT_SECRET} # 환경변수로 관리
            scope:
              - email
              - profile
            redirect-uri: http://localhost:8080/api/login/oauth2/code/google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

---
spring:
  config:
    activate:
      on-profile: prod