version: '3.8'

services:
  # Blue 환경 (Port: 3001)
  frontend-blue:
    # GitHub Actions의 deploy 단계에서 export한 변수들과 매칭됩니다.
    image: ${DOCKERHUB_USERNAME}/${FRONTEND_IMAGE_NAME}:${FRONTEND_IMAGE_TAG}
    container_name: frontend-blue
    environment:
      - TZ=Asia/Seoul
    ports:
      - "3001:80"
    restart: always
    networks:
      - team6-backend
    healthcheck:
      # Nginx 기반이므로 / 경로에 대해 200 OK가 떨어지는지 확인합니다.
      test: ["CMD-SHELL", "curl -f http://localhost:80/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s # 프론트엔드(Nginx)는 기동이 매우 빠르므로 짧게 설정

  # Green 환경 (Port: 3002)
  frontend-green:
    image: ${DOCKERHUB_USERNAME}/${FRONTEND_IMAGE_NAME}:${FRONTEND_IMAGE_TAG}
    container_name: frontend-green
    environment:
      - TZ=Asia/Seoul
    ports:
      - "3002:80"
    restart: always
    networks:
      - team6-backend
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  # 백엔드와 통신이 필요할 수 있으므로 동일한 외부 네트워크를 사용합니다.
  team6-backend:
    external: true